# model
#model_name_or_path: '../llama-7B-fp8'
#model_name_or_path: '/data/models/BLOOM'
model_name_or_path: '/data/models/LLaMA-2/Llama-2-70b-chat-bf'
# data
dataset_name: 'first'
refresh: false
data_tag: 'base'
train_on_inputs: false
data_max_length: 2048
max_length: 2048
# training
# trainer
tag: 'lomo'
output_dir: '/data/outputs'
overwrite_output_dir: true
deepspeed: 'config/ds_config_bf16.json'
do_train: true
do_eval: false
evaluation_strategy: 'epoch'
per_device_train_batch_size: 4
per_device_eval_batch_size: 1
learning_rate: 0.03
weight_decay: 0
num_train_epochs: 1
lr_scheduler_type: 'linear'
warmup: 0.1
clip_grad_norm: 1.0
# please set `resume_from_checkpoint` to load checkpoints.
#resume_from_checkpoint: 'outputs/wic_7B_lomo/output_adamw_hf_lr0.03_bs16_warmup0.1_clipnorm1.0/checkpoint-0'
# please set `save_strategy` (`no`, `epoch`, `steps`) and `save_total_limit` (the max amount of checkpoints) to save checkpoints.
save_strategy: 'steps'
save_steps: 100
save_total_limit: 10
seed: 42
bf16: true
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'acc'
group_by_length: false
#report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: true
predict_with_generate: true
